version: 2.1

jobs:
  build:
    docker:
      - image: circleci/cpp:latest
      
    steps:
      - checkout
      
      - run:
          name: Install CMake
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake
      
      - run:
          name: Build Project
          command: |
            mkdir build
            cd build
            cmake ..
            make
      
      - run:
          name: Run Tests
          command: |
            cd build
            ./MyProject